#!/bin/bash

# ***************************************************************************
# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright (c) 2024, Christoph Zysik
# All rights reserved.
# ***************************************************************************

ECHO_LOG=1
ECHO_LOG_ERROR=1
ECHO_LOG_NOTICE=0
ECHO_LOG_DEBUG=1
ECHO_LOG_TRACE=0

log() {
	if [ $ECHO_LOG = 1 ]; then
		echo "$(date +"%Y-%m-%d %H:%M:%S") - " "$@"
	fi
}

log_error() {
	if [ $ECHO_LOG_ERROR = 1 ]; then
		echo "$(date +"%Y-%m-%d %H:%M:%S") ERROR " "$@"
	fi
}

log_notice() {
	if [ $ECHO_LOG_NOTICE = 1 ]; then
		echo "$(date +"%Y-%m-%d %H:%M:%S") NOTICE " "$@"
	fi
}

log_debug() {
	if [ $ECHO_LOG_DEBUG = 1 ]; then
		echo "$(date +"%Y-%m-%d %H:%M:%S") DEBUG " "$@"
	fi
}

log_trace() {
	if [ $ECHO_LOG_TRACE = 1 ]; then
		echo "$(date +"%Y-%m-%d %H:%M:%S") TRACE " "$@"
	fi
}

error_exit() {
	log_error "$@"
	exit 1
}
